# workflow的名称，会显示在工作流运行页面
name: MainWorkflow

# 工作流执行的契机：push表示每次push代码之后都会执行
on: [push]

jobs:
  # build job 我们用来做持续构建
  build:
    # 构建运行的环境
    runs-on: ubuntu-latest
    # 构建步骤
    steps:
    # 复用 actions/checkout@v1 action，拉取最新代码
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: Build site
      run: |
        npm insatall --legacy-peer-deps
        npm run build
    - name: upload files to OSS
      uses: fangbinwei/aliyun-oss-website-action@v1
      with:
          accessKeyId: ${{ secrets.AccessKeyID }}
          accessKeySecret: ${{ secrets.AccessKeySecret }}
          bucket: taffy-button
          # use your own endpoint
          endpoint: oss-cn-shenzhen.aliyuncs.com
          folder: dist
