name: Build & Upload to TC

on:
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Init node environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Build site
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Install CloudBase-Cli
        run: npm install -g @cloudbase/cli
    
      - name: Login to Tencent CloudBase
        env:
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
        run: tcb login --apiKeyId "$SECRET_ID" --apiKey "$SECRET_KEY"
          
      - name: Deploy dist to Tencent CloudBase
        env:
          ENV_ID: ${{secrets.ENV_ID}}
        run: tcb hosting deploy ./dist . -e "$ENV_ID" -r gz
